package com.commutemate.ride;
import com.commutemate.common.TenantContextHolder; import java.time.Instant; import java.util.List; import java.util.Map; import java.util.UUID; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") public class RideLifecycleController {
 private final RideOfferRepository offers; private final MatchProposalRepository proposals; private final ConfirmedRideRepository rides;
 public RideLifecycleController(RideOfferRepository offers,MatchProposalRepository proposals,ConfirmedRideRepository rides){this.offers=offers;this.proposals=proposals;this.rides=rides;}
 @PostMapping("/match-proposals") @Transactional public MatchProposal request(@RequestBody Map<String,String> body){var c=TenantContextHolder.getRequired();var id=UUID.fromString(body.getOrDefault("rideOfferId",""));var offer=offers.findById(id).orElseThrow(()->new IllegalArgumentException("ride offer not found"));if(!offer.getTenantId().equals(c.tenantId()))throw new SecurityException("offer belongs to another tenant");if(offer.getDriverUserId().equals(c.userId()))throw new IllegalArgumentException("driver cannot request their own ride");if(!offer.getStatus().equals("OPEN"))throw new IllegalArgumentException("ride offer is not open");return proposals.save(new MatchProposal(c.tenantId(),offer.getId(),offer.getDriverUserId(),c.userId()));}
 @GetMapping("/match-proposals/inbox") public List<MatchProposal> inbox(){var c=TenantContextHolder.getRequired();return proposals.findAllByTenantIdAndDriverUserIdAndStatusOrderByCreatedAtDesc(c.tenantId(),c.userId(),"PENDING_DRIVER");}
 @PostMapping("/match-proposals/{id}/accept") @Transactional public Object accept(@PathVariable UUID id){var c=TenantContextHolder.getRequired();var p=proposals.findByIdAndTenantId(id,c.tenantId()).orElseThrow(()->new IllegalArgumentException("proposal not found"));if(!p.getDriverUserId().equals(c.userId()))throw new SecurityException("only the driver can accept this proposal");var offer=offers.findById(p.getRideOfferId()).orElseThrow();offer.reserveSeat();p.accept();var ride=rides.save(new ConfirmedRide(offer,p.getRiderUserId()));return Map.of("proposal",p,"ride",ride,"pickupVisibility","UNLOCKED_FOR_CONFIRMED_PARTICIPANTS");}
 @PostMapping("/match-proposals/{id}/decline") @Transactional public MatchProposal decline(@PathVariable UUID id){var c=TenantContextHolder.getRequired();var p=proposals.findByIdAndTenantId(id,c.tenantId()).orElseThrow(()->new IllegalArgumentException("proposal not found"));if(!p.getDriverUserId().equals(c.userId()))throw new SecurityException("only the driver can decline this proposal");p.decline();return p;}
 @GetMapping("/rides/upcoming") public List<ConfirmedRide> upcoming(){var c=TenantContextHolder.getRequired();return rides.findAllByTenantIdAndDepartureAtAfterOrderByDepartureAt(c.tenantId(),Instant.now());}
}
